### ISSUE TITLE
Create Slack signup functionality

### ISSUE THREAD

**Issue by katrinasperry** [codeforpdx/website#3]
We want new volunteers to be able to easily join our Slack so they can join a product team!

Place in footer below Twitter and Github links, and follow format of those: Slack icon on left, "codeforPDX" text on right.

Here's the link to join Code for PDX Slack: https://join.slack.com/t/codeforpdx/shared_invite/zt-4msr5np3-n5qBye3GG~4hA_7XZkczgA

**Comment by NickSchimek** [comment]
We do have the typeform enabled on our site for onboarding. @katrinasperry - I'm not sure if we want to add this too

**Comment by katrinasperry** [comment]
@NickSchimek The typeform used to cause so much confusion, almost nobody was able to join our slack. But it seems to be working better with virtual events, interestingly. I still think a more discoverable/obvious way to join our slack would be nice. People only use the typeform if we direct them to the URL. It would be nice for visitors to the site to be able to easily find our slack signup, join, and get involved with projects!

**Comment by JetPlaneJJ** [comment]
Hello! I'm new to this group.

I added the group's slack link and a slack icon to the footer in this commit: 6f99e53

However, I'm not sure why running the site locally causes all of the footer svg icons to not show up? I tried using Docker, but the contributing.md seems to be WIP at the moment and Googling didn't seem to work out, so I just did what I've been doing in the past ("bundle exec jekyll")

Thanks

**Comment by NickSchimek** [comment]
> I tried using Docker, but the contributing.md seems to be WIP at the moment and Googling didn't seem to work out, so I just did what I've been doing in the past ("bundle exec jekyll")

Hi @JetPlaneJJ Thank you so much for working on this. Personally I don't use docker and generally test with `bundle exec jekyll serve` I've been very lazy in updating the install docs for this project, usually I'm on top of this sort of stuff. I will get it sorted soon, however if you would like to update it then please submit a PR.

I checked out the branch and the only icon I don't see showing up is the newly added slack icon. All the other icons do show up when running locally. Perhaps because we don''t have an svg icon for it in the folder? maybe we do. I'm not sure. 

It looks like the slack icon is trying to call a cdn. I don't think that's necessary for the small svg images on this static site. Although I'm not opposed to the idea.

<img width="550" alt="Screen Shot 2020-10-24 at 11 31 11 PM" src="https://user-images.githubusercontent.com/19519317/97084340-39a1d000-1651-11eb-9237-1a6512536dc4.png">

**Comment by JetPlaneJJ** [comment]
Hi @NickSchimek, thank you for the reply!

- I don't believe there is an existing slack icon. I also saw that we're using the social-minima theme for the other icons besides DemocracyLab, so I tried to emulate what was already done for DemocracyLab icon: inside the "custom-social-icons.svg". My changes are now here: c41401f

- For me, the console shows the following when I try to preview in the browser after "bundle exec jekyll serve". Perhaps that is why I am still not seeing the loaded icons?

<img width="438" alt="Screen Shot 2020-10-26 at 12 08 31 AM" src="https://user-images.githubusercontent.com/31530784/97143180-6ae8d180-171f-11eb-8c65-28c1cf1ee53b.png">

- Minor unrelated question, but could we perhaps change the "codeforpdx" texts to "GitHub", "Twitter", etc for screenreader accessibility and for people who might not know what the icon is?

**Comment by NickSchimek** [comment]
What operating system are you using?

**Comment by JetPlaneJJ** [comment]
I am on macOS, using Chrome/Safari.

**Comment by NickSchimek** [comment]
Thank you. The error message is really interesting, because those URL's seem abnormal. Also a mac would/should, more or less, work out of the box with very little issue. It seems like a config file that specifies local-host var may be corrupt. Do you know if this issue persists when attempting to access localhost for other projects?

I have one more question, and one possible fix for you to try.

Question:
 - Are any of the other images showing or is it only the svg images?

Can you try this:
In the main app directory run:
`bundle exec jekyll serve -H 0.0.0.0 -P 8550`

And then open a web browser and input:
`0.0.0.0:8550`

**Comment by JetPlaneJJ** [comment]
Hi Nick,
1. I don't believe I have been in a situation where this has happened to me before.
2. Everything else on the website is showing up, including other (not social-minima) icons. It is just the social-minima theme icons that aren't showing up.
<img width="882" alt="Screen Shot 2020-10-27 at 5 14 34 PM" src="https://user-images.githubusercontent.com/31530784/97375372-e493d300-1877-11eb-9699-b756e03df138.png">

3. Thanks! `bundle exec jekyll serve -H 0.0.0.0 -P 8550` appears to work for me. All of the icons now show up. If I may ask for future reference, what exactly did this syntax do?

**Comment by NickSchimek** [comment]
> Everything else on the website is showing up, including other (not social-minima) icons

That is very interesting. 

> what exactly did this syntax do?

When `jekyll serve` is ran it sets the host (-H) and port (-P) to 127.0.0.1 (localhost) and 4000 respectively. 

with `-H 0.0.0.0 -P 8550` it explicitly sets it to those values. see the [Jekyll config options here](https://jekyllrb.com/docs/configuration/options/#serve-command-options). I chose 8550 sort of arbitrarily. Host 0.0.0.0 tells your computer to accept all incoming connections regardless of the host address being used. I sometimes use host 0.0.0.0 to serve the website across a wifi connection so that I can view the site with other computers or mobile devices to see how it looks.

**Comment by JetPlaneJJ** [comment]
Thank you!
