### ISSUE TITLE
Contact Us form

### ISSUE THREAD

**Issue by katrinasperry** [codeforpdx/website#42]
need to think about how to handle contact us form:

- needs to be free
- Nick has backend started that we could hook into
- or we can use a library

anyone is welcome to research! comment if you find anything interesting.

**Comment by ghost** [comment]
https://www.sendinblue.com/
This may be a suitable option I'm not sure but it is 300 emails a day for free you can probably stagger the emails if you had to I'm not sure if we have an email list. If I remember correctly we were just looking to automate emails and maybe an inbox.

**Comment by NickSchimek** [comment]
Looks like that requires an api key to use, which we would not be able to store safely since this is a static site.

There are some options listed here: https://jekyllrb.com/resources/#forms

99inbound looks good, but I haven't really researched much.  (It allows 100 form submissions a month on the free plan which should be plenty)

As long as whichever one we choose does not require a credit card to sign up then I'm good with it. Oh and it needs to be able to be customized to match our design.

**Comment by ghost** [comment]
@NickSchimek okay thank I'll look into that last I heard you were working on this. Are you still doing this I just don't want to step on your toes if you already have something?

**Comment by NickSchimek** [comment]
No, I'm not working on it. Feel free to take it.

**Comment by ghost** [comment]
Okay, thanks ill go ahead and do that.
